/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:1426f64e-2a2a-49ac-bf5e-3e521ee9a5ec",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_wPmhIxNmD",
    "aws_user_pools_web_client_id": "1ug9aqbjib9l9m2d927e2fo8i7",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://b3cl5znfjne6jhehyayu3cu7qi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "myclassawsversion8a63240d05894031920b37125c6093220207-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
